### PR TITLE
Correct a pathin grid search

### PR DESCRIPTION
**Pull request by DrewGalbraith**

### CODE REVIEW

**Review by JayOrten — APPROVED** [review]
Did you ever hear the tragedy of Darth Plagueis "the wise"? I thought not. It's not a story the Jedi would tell you. It's a Sith legend. Darth Plagueis was a Dark Lord of the Sith, so powerful and so wise he could use the Force to influence the midichlorians to create life... He had such a knowledge of the dark side that he could even keep the ones he cared about from dying. The dark side of the Force is a pathway to many abilities some consider to be unnatural. He became so powerful... the only thing he was afraid of was losing his power, which eventually, of course, he did. Unfortunately, he taught his apprentice everything he knew, then his apprentice killed him in his sleep. It's ironic he could save others from death, but not himself.

**Comment by nprisbrey** [comment]
Dang @JayOrten, I feel like I see PRs in a whole new light now.........

**Review by nprisbrey — APPROVED** [review]
Nice and simple; I like it.

**Comment by nprisbrey** [comment]
In the hushed shadows of cyberspace's hall,
A single line of code, a silent thrall,
It creeps through networks with silent feet,
A semicolon’s shift, a subtle deceit.

From errors breed, the chaos seeds,
A misplaced loop, where darkness leads,
Through cities of silicon, it quietly spreads,
A ripple through systems, a thread of dread.

Behold how empires on pixels rely,
That even the smallest byte can defy,
So fear the code, the architect’s lore,
For what seems benign can open the door.

**Pull request merged**
