### PR TITLE
Add the tokenizer for c4 to repo

### PR DESCRIPTION
**Pull request by DrewGalbraith**

### CODE REVIEW

**Comment by DrewGalbraith** [comment]
pfft Nathan isn't even a Pro GitHub user

**Comment by DrewGalbraith** [comment]
I had extra commits from other branches slip in here somehow. 😤  I didn't even use `git add .` I'll have to fix that.

**Comment by nprisbrey** [comment]
@DrewGalbraith, does [1fd4f86](https://github.com/DRAGNLabs/301r_retnet/pull/61/commits/1fd4f86547ecc9f16f5d7aeb819d7427b035980d) do what you were looking for?

**Review by KimballNJardine — COMMENTED** [review]
This looks fine. I just want to make sure with everyone that we want to add the tokenizer itself to the repo before doing so.

**Comment by DrewGalbraith** [comment]
> @DrewGalbraith, does [1fd4f86](https://github.com/DRAGNLabs/301r_retnet/pull/61/commits/1fd4f86547ecc9f16f5d7aeb819d7427b035980d) do what you were looking for?

I actually haven't verified that yet, it's one of my back burner projects

**Comment by nprisbrey** [comment]
Sounds like from Slack that this is going to move to Hugging Face. Do you want to take charge of that @DrewGalbraith?

**Comment by DrewGalbraith** [comment]
Yeah, @KimballNJardine, let's go ahead and delete this branch.

**Pull request closed without merging**
